# Verificar se a API está funcionando
GET http://localhost:8085/health HTTP/1.1

###
# @name createClient1
# Criar o primeiro cliente (John Doe)
POST http://localhost:8085/clients HTTP/1.1
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@j.com"
}

###
# Salvar o ID do primeiro cliente
@clientId1 = {{createClient1.response.body.ID}}

###
# @name createAccount1
# Criar a conta para o primeiro cliente (John Doe)
POST http://localhost:8085/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "{{clientId1}}"
}

###
# Salvar o ID da conta do primeiro cliente
@accountId1 = {{createAccount1.response.body.ID}}

###
# @name createClient2
# Criar o segundo cliente (Jane Doe)
POST http://localhost:8085/clients HTTP/1.1
Content-Type: application/json

{
    "name": "Jane Wasley",
    "email": "jane@j.com"
}

###
# Salvar o ID do segundo cliente
@clientId2 = {{createClient2.response.body.ID}}

###
# @name createAccount2
# Criar a conta para o segundo cliente (Jane Doe)
POST http://localhost:8085/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "{{clientId2}}"
}

###
# Salvar o ID da conta do segundo cliente
@accountId2 = {{createAccount2.response.body.ID}}

###
# Realizar uma transação entre as contas dos dois clientes
# Transferir 100 da conta do John Doe para a conta da Jane Doe
POST http://localhost:8085/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "{{accountId1}}",
    "account_id_to": "{{accountId2}}",
    "amount": 100
}