@baseUrl = http://localhost:3000


### Buscar todos os produtos
GET {{baseUrl}}/products


### Criar um cliente e salvar o ID
# @name createClient
POST {{baseUrl}}/clients
Content-Type: application/json

{
    "name": "João da Silva",
    "email": "joao.silva@example.com",
    "document": "123456789",
    "street": "Rua das Flores",
    "number": "123",
    "complement": "Apto 123",
    "city": "São Paulo",
    "state": "SP",
    "zipCode": "12345-678"
}

### Salvar o ID do cliente da resposta
@clientId = {{createClient.response.body.id}}

### Criar um produto e salvar o ID
# @name createProduct
POST {{baseUrl}}/products
Content-Type: application/json

{
    "name": "Product 1",
    "description": "Product 1 description",
    "purchasePrice": 100,
    "stock": 10
}


### Salvar o ID do produto da resposta
@productId = {{createProduct.response.body.id}}

### Buscar todos os produtos
GET {{baseUrl}}/products

### Buscar produto por ID
GET {{baseUrl}}/products/{{productId}}


### Criar um pedido (checkout) usando os IDs salvos
# @name createOrder
POST {{baseUrl}}/checkout
Content-Type: application/json

{
    "clientId": "{{clientId}}",
    "products": [
        {
            "productId": "{{productId}}",
            "quantity": 1
        }
    ]
}

### Salvar o ID da invoice da resposta do checkout
@invoiceId = {{createOrder.response.body.invoiceId}}

### Buscar invoice por ID
GET {{baseUrl}}/invoice/{{invoiceId}} 